# Generated by Django 4.0.4 on 2022-06-09 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='bus_id',
            new_name='bus',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='passenger_id',
            new_name='passenger',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='route_id',
            new_name='route',
        ),
    ]
